#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  mitel-ov:
    external:
      name: mitel-ov

services:
   # api server
  org1.com:
    image: nodesdk:1.0.0
    container_name: api.org1.com
    ports:
      - "4002:4001"
    environment:
      - ORG=org1
      - PORT=4001
    volumes:
     - ../crypto-config:/usr/src/artifacts/channel/crypto-config
     - ../channel-artifacts:/usr/src/artifacts/channel
     - .:/usr/src/artifacts
    networks:
      - mitel-ov
  